#!/usr/bin/env tsx
/**
 * Manual-mode translation bundler.
 *
 * Packages the translation prompt + the FR aggregated.json into a
 * single copy-pasteable bundle for a web-chat LLM, with the
 * translatable-paths allowlist substituted into the prompt body.
 *
 * See docs/specs/website/i18n.md §3.2.
 */
import { Command } from "commander";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createLogger } from "./lib/logger";
import { hashString } from "./lib/hash";
import * as paths from "./lib/paths";
import { stripFrontmatter } from "./prepare-manual-analysis";
import { normalizeArgv } from "./lib/cli-args";
import { TRANSLATABLE_PATHS } from "./lib/translatable-paths";

const log = createLogger({ script: "prepare-manual-translation" });

/** Language-code → human-readable target-language label for prompt substitution. */
export const LANGUAGE_LABELS: Readonly<Record<string, string>> = {
  en: "English",
};

const ALLOWLIST_START_MARKER = "<!-- PARITY_ALLOWLIST_START -->";
const ALLOWLIST_END_MARKER = "<!-- PARITY_ALLOWLIST_END -->";
const ALLOWLIST_PLACEHOLDER = "{{ALLOWLIST}}";
const TARGET_LANGUAGE_PLACEHOLDER_RE = /\{\{TARGET_LANGUAGE\}\}/g;

export interface PrepareManualTranslationOptions {
  candidate: string;
  version: string;
  lang: string;
  force?: boolean;
}

/** Render TRANSLATABLE_PATHS as a markdown bullet list of inline-coded paths. */
export function renderAllowlistMarkdown(
  paths: ReadonlyArray<string> = TRANSLATABLE_PATHS,
): string {
  return paths.map((p) => `- \`${p}\``).join("\n");
}

/**
 * Substitute `{{TARGET_LANGUAGE}}` and the allowlist marker block in
 * the prompt body. Throws if either marker is missing.
 */
export function substitutePromptPlaceholders(
  promptBody: string,
  targetLanguage: string,
  allowlistMarkdown: string,
): string {
  if (!promptBody.includes(ALLOWLIST_START_MARKER)) {
    throw new Error(
      `Prompt body is missing ${ALLOWLIST_START_MARKER}. ` +
        `Cannot substitute the parity allowlist.`,
    );
  }
  const replaced = promptBody.replace(
    new RegExp(
      `${escapeRegExp(ALLOWLIST_START_MARKER)}[\\s\\S]*?${escapeRegExp(
        ALLOWLIST_END_MARKER,
      )}`,
    ),
    `${ALLOWLIST_START_MARKER}\n${allowlistMarkdown}\n${ALLOWLIST_END_MARKER}`,
  );
  // Also replace any literal `{{ALLOWLIST}}` placeholder if present
  // (defensive — older prompt drafts used it).
  const withAllowlist = replaced.replaceAll(
    ALLOWLIST_PLACEHOLDER,
    allowlistMarkdown,
  );
  const withLanguage = withAllowlist.replace(
    TARGET_LANGUAGE_PLACEHOLDER_RE,
    targetLanguage,
  );
  return withLanguage;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Build the combined translation-bundle.txt content. */
export function buildTranslationBundle(opts: {
  candidate: string;
  version: string;
  lang: string;
  targetLanguage: string;
  promptPath: string;
  promptBody: string;
  promptSha256: string;
  aggregatedJson: string;
  generatedAt: string;
}): string {
  const divider = "=".repeat(60);
  return [
    divider,
    "ÉLECTION 2027 — TRANSLATION PROMPT BUNDLE",
    `Generated: ${opts.generatedAt}`,
    `Candidate: ${opts.candidate}`,
    `Version: ${opts.version}`,
    `Language: ${opts.lang} (${opts.targetLanguage})`,
    `Prompt file: ${opts.promptPath}`,
    `Prompt SHA256: ${opts.promptSha256}`,
    "Mode: manual-webchat",
    divider,
    "",
    "INSTRUCTIONS FOR THE CHAT MODEL",
    "-".repeat(31),
    `You are translating the FR aggregated analysis below into ${opts.targetLanguage}.`,
    "Read the prompt VERBATIM, then apply it to the FR JSON that follows.",
    "Return ONLY a single JSON object with the same schema — no",
    "commentary, no markdown fences, no prefatory text.",
    "",
    divider,
    `PROMPT (verbatim from ${opts.promptPath}, with allowlist + language substituted)`,
    divider,
    "",
    opts.promptBody,
    "",
    divider,
    "FR AGGREGATED.JSON (input to translate)",
    divider,
    "",
    opts.aggregatedJson,
    "",
    divider,
    "END OF BUNDLE — return translated JSON only",
    divider,
    "",
  ].join("\n");
}

const README_TEMPLATE = (
  candidate: string,
  version: string,
  lang: string,
  targetLanguage: string,
  promptSha256: string,
) =>
  `# Manual Translation Bundle — ${candidate} (${version}, ${lang})

> Generated by \`scripts/prepare-manual-translation.ts\`. Files in this
> folder are \`.gitignore\`'d (except this README).

## What's here

- \`translation-bundle.txt\` — translation prompt + FR \`aggregated.json\`.
  Copy-paste into a chat UI.
- \`aggregated.json\` — context copy of the FR canonical file.

## Target language

- Code: \`${lang}\`
- Label: ${targetLanguage}

## Prompt SHA256

\`${promptSha256}\`

## Per-UI flow

1. Open a new chat with your chosen translator model (e.g. Claude
   Opus, GPT-5).
2. Paste \`translation-bundle.txt\` (or upload if the UI supports it).
3. Save the JSON response locally, e.g. \`~/Downloads/aggregated.${lang}.json\`.
4. Ingest:
   \`\`\`
   npm run ingest-translation -- \\
     --candidate ${candidate} --version ${version} \\
     --lang ${lang} \\
     --attested-version "<exact model string from UI>" \\
     --attested-by "<your handle>" \\
     --input ~/Downloads/aggregated.${lang}.json
   \`\`\`
5. After human review, promote the draft:
   \`\`\`
   mv candidates/${candidate}/versions/${version}/aggregated.${lang}.draft.json \\
      candidates/${candidate}/versions/${version}/aggregated.${lang}.json
   \`\`\`

See \`docs/specs/website/i18n.md\` §3 for the full flow.
`;

/** Prepare a manual-translation bundle under `_translation/`. */
export async function prepareManualTranslation(
  opts: PrepareManualTranslationOptions,
): Promise<{
  bundlePath: string;
  promptSha256: string;
  targetLanguage: string;
}> {
  const { candidate, version, lang, force = false } = opts;

  if (!/^[a-z]{2}$/.test(lang)) {
    throw new Error(
      `--lang must be an ISO 639-1 lowercase code (got "${lang}")`,
    );
  }
  if (lang === "fr") {
    throw new Error(
      `Cannot prepare a translation bundle for --lang fr; FR is canonical.`,
    );
  }

  const targetLanguage = LANGUAGE_LABELS[lang];
  if (!targetLanguage) {
    throw new Error(
      `No human label registered for lang "${lang}". ` +
        `Add an entry to LANGUAGE_LABELS in scripts/prepare-manual-translation.ts.`,
    );
  }

  const verDir = paths.versionDir(candidate, version);
  if (!paths.pathExists(verDir)) {
    throw new Error(`Version directory not found: ${verDir}`);
  }

  const aggregatedPath = join(verDir, "aggregated.json");
  if (!paths.pathExists(aggregatedPath)) {
    throw new Error(
      `aggregated.json not found at ${aggregatedPath}. ` +
        `Aggregation must complete (and be promoted from .draft) first.`,
    );
  }

  const bundleDir = join(verDir, "_translation", lang);
  if (paths.pathExists(bundleDir)) {
    const { readdir } = await import("node:fs/promises");
    const existing = await readdir(bundleDir);
    const nonEmpty = existing.filter((n) => n !== ".gitkeep");
    if (nonEmpty.length > 0 && !force) {
      throw new Error(
        `_translation/${lang}/ already exists with content (${nonEmpty.length} entries). ` +
          `Re-run with --force to overwrite.`,
      );
    }
  }

  const promptPath = "prompts/translate-aggregated.md";
  const promptAbs = resolve(process.cwd(), promptPath);
  const promptRaw = await readFile(promptAbs, "utf-8");
  const promptSha256 = hashString(promptRaw);
  const promptBodyRaw = stripFrontmatter(promptRaw);
  const allowlistMd = renderAllowlistMarkdown();
  const promptBody = substitutePromptPlaceholders(
    promptBodyRaw,
    targetLanguage,
    allowlistMd,
  );

  const aggregatedJson = await readFile(aggregatedPath, "utf-8");
  const bundle = buildTranslationBundle({
    candidate,
    version,
    lang,
    targetLanguage,
    promptPath,
    promptBody,
    promptSha256,
    aggregatedJson,
    generatedAt: new Date().toISOString(),
  });

  await mkdir(bundleDir, { recursive: true });
  const bundlePath = join(bundleDir, "translation-bundle.txt");
  await writeFile(bundlePath, bundle, "utf-8");
  await writeFile(join(bundleDir, "aggregated.json"), aggregatedJson, "utf-8");
  await writeFile(
    join(bundleDir, "README.md"),
    README_TEMPLATE(candidate, version, lang, targetLanguage, promptSha256),
    "utf-8",
  );

  log.info(
    { bundlePath, promptSha256, lang, targetLanguage },
    "Manual translation bundle prepared",
  );

  return { bundlePath, promptSha256, targetLanguage };
}

// CLI
const program = new Command();
program
  .name("prepare-manual-translation")
  .description(
    "Produce a copy-pasteable translation bundle under _translation/<lang>/",
  )
  .requiredOption("--candidate <id>", "Candidate ID")
  .requiredOption("--version <date>", "Version date (YYYY-MM-DD)")
  .requiredOption("--lang <code>", "ISO 639-1 target language code (e.g. en)")
  .option("--force", "Overwrite existing _translation/<lang>/ folder", false)
  .action(async (opts) => {
    try {
      await prepareManualTranslation({
        candidate: opts.candidate,
        version: opts.version,
        lang: opts.lang,
        force: opts.force,
      });
    } catch (err) {
      log.error(
        { error: err instanceof Error ? err.message : String(err) },
        "Failed to prepare manual translation bundle",
      );
      process.exit(1);
    }
  });

const isDirectRun =
  process.argv[1] &&
  (process.argv[1].endsWith("/prepare-manual-translation.ts") ||
    process.argv[1].endsWith("/prepare-manual-translation.js"));
if (isDirectRun) {
  program.parse(normalizeArgv(process.argv));
}
