#!/usr/bin/env tsx
/**
 * Manual-mode aggregation bundler.
 *
 * Packages the aggregation prompt + all raw-outputs + sources.md into a
 * single copy-pasteable bundle for a web-chat LLM.
 *
 * See docs/specs/data-pipeline/analysis-modes.md ("Mode 2 — manual-webchat")
 */
import { Command } from "commander";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createLogger } from "./lib/logger";
import { hashString } from "./lib/hash";
import * as paths from "./lib/paths";
import { stripFrontmatter } from "./prepare-manual-analysis";

const log = createLogger({ script: "prepare-manual-aggregation" });

export interface PrepareManualAggregationOptions {
  candidate: string;
  version: string;
  force?: boolean;
}

export interface RawOutputEntry {
  filename: string;
  content: string;
}

/** Build the combined prompt-bundle.txt for aggregation. */
export function buildAggregationBundle(opts: {
  candidate: string;
  version: string;
  promptPath: string;
  promptBody: string;
  promptSha256: string;
  sourcesMd: string;
  rawOutputs: RawOutputEntry[];
  generatedAt: string;
}): string {
  const divider = "=".repeat(60);
  const lines: string[] = [
    divider,
    "ÉLECTION 2027 — AGGREGATION PROMPT BUNDLE",
    `Generated: ${opts.generatedAt}`,
    `Candidate: ${opts.candidate}`,
    `Version: ${opts.version}`,
    `Prompt file: ${opts.promptPath}`,
    `Prompt SHA256: ${opts.promptSha256}`,
    `Raw outputs included: ${opts.rawOutputs.length}`,
    "Mode: manual-webchat",
    divider,
    "",
    "INSTRUCTIONS FOR THE CHAT MODEL",
    "-".repeat(31),
    "You are being used as an aggregator model. Read the prompt below",
    "VERBATIM, then apply it to the raw analyses that follow. Return",
    "ONLY the JSON structure described — no commentary, no markdown",
    "fences, no prefatory text.",
    "",
    divider,
    `PROMPT (verbatim from ${opts.promptPath})`,
    divider,
    "",
    opts.promptBody,
    "",
    divider,
    "SOURCES.md (context)",
    divider,
    "",
    opts.sourcesMd,
    "",
  ];

  for (const ro of opts.rawOutputs) {
    lines.push(
      divider,
      `RAW OUTPUT — ${ro.filename}`,
      divider,
      "",
      ro.content,
      "",
    );
  }

  lines.push(
    divider,
    "END OF BUNDLE — return aggregated JSON only",
    divider,
    "",
  );
  return lines.join("\n");
}

const README_TEMPLATE = (
  candidate: string,
  version: string,
  promptSha256: string,
  rawCount: number,
) =>
  `# Manual Aggregation Bundle — ${candidate} (${version})

> Generated by \`scripts/prepare-manual-aggregation.ts\`. Files in this
> folder are \`.gitignore\`'d (except this README).

## What's here

- \`prompt-bundle.txt\` — the aggregation prompt + \`sources.md\` + all
  ${rawCount} raw analyses concatenated. Copy-paste into a chat UI.
- \`sources.md\` — context copy.

## Prompt SHA256

\`${promptSha256}\`

## Per-UI flow (brief)

1. Open a new chat with your chosen aggregator model.
2. Paste \`prompt-bundle.txt\` (or upload if the UI supports it).
3. Copy the JSON response to a local file, e.g. \`~/Downloads/aggregated.json\`.
4. Ingest:
   \`\`\`
   npm run ingest-aggregated -- \\
     --candidate ${candidate} --version ${version} \\
     --mode manual-webchat \\
     --provider <anthropic|openai|google|...> \\
     --attested-version "<exact model string from UI>" \\
     --attested-by "<your handle>" \\
     --file ~/Downloads/aggregated.json
   \`\`\`

See \`docs/specs/data-pipeline/analysis-modes.md\` for the full flow
and review requirements.
`;

/**
 * Prepare a manual-aggregation bundle under `_manual-aggregation/`.
 */
export async function prepareManualAggregation(
  opts: PrepareManualAggregationOptions,
): Promise<{ bundlePath: string; promptSha256: string; rawOutputCount: number }> {
  const { candidate, version, force = false } = opts;

  const verDir = paths.versionDir(candidate, version);
  if (!paths.pathExists(verDir)) {
    throw new Error(`Version directory not found: ${verDir}.`);
  }

  const sourcesPath = join(verDir, "sources.md");
  if (!paths.pathExists(sourcesPath)) {
    throw new Error(`sources.md not found at ${sourcesPath}.`);
  }

  const rawDir = paths.rawOutputsDir(candidate, version);
  if (!paths.pathExists(rawDir)) {
    throw new Error(
      `raw-outputs/ not found at ${rawDir}. Run analysis (any mode) first.`,
    );
  }

  const rawFiles = (await readdir(rawDir))
    .filter((n) => n.endsWith(".json"))
    .sort();
  if (rawFiles.length === 0) {
    throw new Error(
      `No JSON files in ${rawDir}. Aggregation requires at least one raw analysis.`,
    );
  }

  const bundleDir = join(verDir, "_manual-aggregation");
  if (paths.pathExists(bundleDir)) {
    const existing = await readdir(bundleDir);
    const nonEmpty = existing.filter((n) => n !== ".gitkeep");
    if (nonEmpty.length > 0 && !force) {
      throw new Error(
        `_manual-aggregation/ already exists with content (${nonEmpty.length} entries). Re-run with --force to overwrite.`,
      );
    }
  }

  const promptPath = "prompts/aggregate-analyses.md";
  const promptAbs = resolve(process.cwd(), promptPath);
  const promptRaw = await readFile(promptAbs, "utf-8");
  const promptSha256 = hashString(promptRaw);
  const promptBody = stripFrontmatter(promptRaw);
  const sourcesMd = await readFile(sourcesPath, "utf-8");

  const rawOutputs: RawOutputEntry[] = [];
  for (const filename of rawFiles) {
    const content = await readFile(join(rawDir, filename), "utf-8");
    rawOutputs.push({ filename, content });
  }

  const bundle = buildAggregationBundle({
    candidate,
    version,
    promptPath,
    promptBody,
    promptSha256,
    sourcesMd,
    rawOutputs,
    generatedAt: new Date().toISOString(),
  });

  await mkdir(bundleDir, { recursive: true });
  const bundlePath = join(bundleDir, "prompt-bundle.txt");
  await writeFile(bundlePath, bundle, "utf-8");
  await writeFile(join(bundleDir, "sources.md"), sourcesMd, "utf-8");
  await writeFile(
    join(bundleDir, "README.md"),
    README_TEMPLATE(candidate, version, promptSha256, rawOutputs.length),
    "utf-8",
  );

  log.info(
    { bundlePath, promptSha256, rawOutputCount: rawOutputs.length },
    "Manual aggregation bundle prepared",
  );
  return { bundlePath, promptSha256, rawOutputCount: rawOutputs.length };
}

// CLI
const program = new Command();
program
  .name("prepare-manual-aggregation")
  .description("Produce a copy-pasteable aggregation bundle under _manual-aggregation/")
  .requiredOption("--candidate <id>", "Candidate ID")
  .requiredOption("--version <date>", "Version date (YYYY-MM-DD)")
  .option("--force", "Overwrite existing _manual-aggregation/ folder", false)
  .action(async (opts) => {
    try {
      await prepareManualAggregation({
        candidate: opts.candidate,
        version: opts.version,
        force: opts.force,
      });
    } catch (err) {
      log.error(
        { error: err instanceof Error ? err.message : String(err) },
        "Failed to prepare manual aggregation bundle",
      );
      process.exit(1);
    }
  });

const isDirectRun =
  process.argv[1] &&
  (process.argv[1].endsWith("/prepare-manual-aggregation.ts") ||
    process.argv[1].endsWith("/prepare-manual-aggregation.js"));
if (isDirectRun) {
  program.parse();
}
