#!/usr/bin/env tsx
/**
 * Manual-mode analysis bundler.
 *
 * Generates a self-contained prompt bundle the operator pastes into a
 * web-chat LLM (ChatGPT, Claude.ai, Gemini). No network calls.
 *
 * See docs/specs/data-pipeline/analysis-modes.md ("Mode 2 — manual-webchat")
 */
import { Command } from "commander";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createLogger } from "./lib/logger";
import { hashString } from "./lib/hash";
import * as paths from "./lib/paths";
import { normalizeArgv } from "./lib/cli-args";

const log = createLogger({ script: "prepare-manual-analysis" });

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Load the valid-full analysis fixture as a pretty-printed JSON string.
 * The fixture is resolved relative to this script so it works regardless
 * of where the CLI is invoked from.
 */
async function loadReferenceExample(): Promise<string> {
  const fixturePath = resolve(
    __dirname,
    "lib/fixtures/analysis-output/valid-full.json",
  );
  const raw = await readFile(fixturePath, "utf-8");
  // Reparse + reserialize to normalize whitespace and catch accidental drift.
  return JSON.stringify(JSON.parse(raw), null, 2);
}

export interface PrepareManualAnalysisOptions {
  candidate: string;
  version: string;
  force?: boolean;
}

/** Strip one leading YAML frontmatter block from prompt markdown. */
export function stripFrontmatter(text: string): string {
  return text.replace(/^---\n[\s\S]*?\n---\n/, "");
}

/** Build the combined prompt-bundle.txt content. */
export function buildBundle(opts: {
  candidate: string;
  version: string;
  promptPath: string;
  promptBody: string;
  promptSha256: string;
  sourcesMd: string;
  generatedAt: string;
  referenceExampleJson?: string;
}): string {
  const divider = "=".repeat(60);
  const base = [
    divider,
    "ÉLECTION 2027 — ANALYSIS PROMPT BUNDLE",
    `Generated: ${opts.generatedAt}`,
    `Candidate: ${opts.candidate}`,
    `Version: ${opts.version}`,
    `Prompt file: ${opts.promptPath}`,
    `Prompt SHA256: ${opts.promptSha256}`,
    "Mode: manual-webchat",
    divider,
    "",
    "INSTRUCTIONS FOR THE CHAT MODEL",
    "-".repeat(31),
    "You are being used as an analyst model for a transparency-oriented",
    "public website. Follow the prompt below VERBATIM. Return ONLY the",
    "JSON structure described — no commentary, no markdown fences, no",
    "prefatory text.",
    "",
    "IMPORTANT — the 'Compact shape' in the prompt is a summary, not the",
    "full schema. The REFERENCE EXAMPLE appended at the end of this bundle",
    "shows every required field, including the exact shape of nested",
    "objects in `dimensions.*.problems_addressed[]` (objects, not strings),",
    "`intergenerational.magnitude_estimate` (object with",
    "`value`/`units`/`confidence`/`caveats`),",
    "`intergenerational.impact_on_25yo_in_2027` / `impact_on_65yo_in_2027`",
    "(objects with per-theme cells + `narrative_summary`),",
    "`unsolved_problems[]` (keys: `problem`, `why_unsolved`,",
    "`severity_if_unsolved`, `source_refs` — no other keys),",
    "and `downside_scenarios[]` (keys: `scenario`, `trigger`, `probability`,",
    "`severity`, `reasoning` — no other keys).",
    "",
    "The schema is STRICT: any extra keys will be rejected at ingest.",
    "",
    "Match the REFERENCE EXAMPLE's structure EXACTLY. Your values must",
    "be grounded in the candidate's sources.md below — do not copy the",
    "example's content.",
    "",
    divider,
    `PROMPT (verbatim from ${opts.promptPath})`,
    divider,
    "",
    opts.promptBody,
    "",
    divider,
    "SOURCES.md",
    divider,
    "",
    opts.sourcesMd,
    "",
  ];

  if (opts.referenceExampleJson) {
    base.push(
      divider,
      "REFERENCE EXAMPLE — valid output shape",
      divider,
      "",
      "The following JSON validates against AnalysisOutputSchema. Use it as",
      "a structural template. Replace every value with analysis of THIS",
      "candidate's program — do not reuse the example's content. Keep the",
      "same keys and the same nesting.",
      "",
      opts.referenceExampleJson,
      "",
    );
  }

  base.push(
    divider,
    "END OF BUNDLE — return JSON only",
    divider,
    "",
  );
  return base.join("\n");
}

const README_TEMPLATE = (candidate: string, version: string, promptSha256: string) =>
  `# Manual Analysis Bundle — ${candidate} (${version})

> Generated by \`scripts/prepare-manual-analysis.ts\`. Files in this folder
> are \`.gitignore\`'d (except this README).
>
> **Do not commit chat transcripts or pasted responses.**

## What's here

- \`prompt-bundle.txt\` — the full prompt + \`sources.md\`. Copy-paste this
  into a chat UI, or upload as a file if the UI supports it.
- \`sources.md\` — a copy of the candidate's consolidated program, in case
  the UI prefers file attachments.
- \`expected-filenames.txt\` — suggested raw-output filenames per model.

## Prompt SHA256 (record at ingest time)

\`${promptSha256}\`

This hash must match when you run \`npm run ingest-raw-output\`; any
mismatch means the canonical prompt changed between bundle generation
and ingest.

## Step-by-step per chat UI

### ChatGPT (chat.openai.com)

1. Open a new conversation with your chosen model (e.g. GPT-5 thinking).
2. Upload \`sources.md\` via the attach button (preferred) OR include it
   inline \u2014 the bundle already contains it.
3. Paste the contents of \`prompt-bundle.txt\`.
4. Wait for the JSON response. If the model wraps it in \`\`\`json fences,
   the ingest script will strip one layer automatically.
5. Copy the JSON to a local file (e.g. \`~/Downloads/chatgpt.json\`).
6. Ingest:
   \`\`\`
   npm run ingest-raw-output -- \\
     --candidate ${candidate} --version ${version} \\
     --model <model-slug> \\
     --mode manual-webchat \\
     --provider openai \\
     --attested-version "<exact model string from UI>" \\
     --attested-by "<your handle>" \\
     --file ~/Downloads/chatgpt.json
   \`\`\`

### Claude.ai (claude.ai)

1. Open a new conversation with Claude Opus (or your chosen model).
2. Attach \`sources.md\` (preferred) or paste inline.
3. Paste \`prompt-bundle.txt\` contents.
4. Copy the JSON response to a local file.
5. Ingest with \`--provider anthropic\`.

### Gemini (gemini.google.com)

1. Open a new conversation with Gemini 2.5 Pro (or newer).
2. Attach \`sources.md\`.
3. Paste \`prompt-bundle.txt\` contents.
4. Copy the JSON response to a local file.
5. Ingest with \`--provider google\`.

## Troubleshooting

- **Validation failure on ingest:** re-run the prompt in the chat,
  ask the model to emit strictly valid JSON without commentary. Do
  not hand-edit the output file.
- **Model returned truncated JSON:** ask the chat UI to continue; copy
  the concatenated full response.
- **You can't remember which model you ran:** rerun. Attestation must
  match reality.
`;

const EXPECTED_FILENAMES_TEMPLATE = () =>
  `# One JSON file per model, placed at
#   candidates/<id>/versions/<date>/raw-outputs/<slug>.json
#
# Suggested slugs — use the exact model version your chat UI reports
# where possible, kebab-cased. Examples:
#
claude-opus-4-1
gpt-5-thinking
gemini-2-5-pro
mistral-large-2
grok-3
`;

/**
 * Prepare a manual-analysis bundle under `_manual/`.
 */
export async function prepareManualAnalysis(
  opts: PrepareManualAnalysisOptions,
): Promise<{ bundlePath: string; promptSha256: string }> {
  const { candidate, version, force = false } = opts;

  const verDir = paths.versionDir(candidate, version);
  if (!paths.pathExists(verDir)) {
    throw new Error(
      `Version directory not found: ${verDir}. Scaffold the candidate first.`,
    );
  }

  const sourcesPath = join(verDir, "sources.md");
  if (!paths.pathExists(sourcesPath)) {
    throw new Error(
      `sources.md not found at ${sourcesPath}. Run consolidation (or drop sources.md in place) first.`,
    );
  }

  const bundleDir = join(verDir, "_manual");
  if (paths.pathExists(bundleDir)) {
    const existing = await readdir(bundleDir);
    const nonEmpty = existing.filter((n) => n !== ".gitkeep");
    if (nonEmpty.length > 0 && !force) {
      throw new Error(
        `_manual/ already exists with content (${nonEmpty.length} entries). Re-run with --force to overwrite.`,
      );
    }
  }

  const promptPath = "prompts/analyze-candidate.md";
  const promptAbs = resolve(process.cwd(), promptPath);
  const promptRaw = await readFile(promptAbs, "utf-8");
  const promptSha256 = hashString(promptRaw);
  const promptBody = stripFrontmatter(promptRaw);
  const sourcesMd = await readFile(sourcesPath, "utf-8");

  // Load the valid-full fixture as a REFERENCE EXAMPLE so chat models
  // see the exact nested shape (dimensions.*.problems_addressed[] as
  // objects, intergenerational.magnitude_estimate as an object, etc.).
  // The canonical prompt's "Compact shape" is too lossy on its own.
  // This does not modify the canonical prompt hash — it only enriches
  // the manual-webchat wrapper.
  const referenceExampleJson = await loadReferenceExample();

  const bundle = buildBundle({
    candidate,
    version,
    promptPath,
    promptBody,
    promptSha256,
    sourcesMd,
    generatedAt: new Date().toISOString(),
    referenceExampleJson,
  });

  await mkdir(bundleDir, { recursive: true });
  const bundlePath = join(bundleDir, "prompt-bundle.txt");
  await writeFile(bundlePath, bundle, "utf-8");
  await writeFile(join(bundleDir, "sources.md"), sourcesMd, "utf-8");
  await writeFile(
    join(bundleDir, "README.md"),
    README_TEMPLATE(candidate, version, promptSha256),
    "utf-8",
  );
  await writeFile(
    join(bundleDir, "expected-filenames.txt"),
    EXPECTED_FILENAMES_TEMPLATE(),
    "utf-8",
  );

  log.info(
    { bundlePath, promptSha256 },
    "Manual analysis bundle prepared",
  );
  return { bundlePath, promptSha256 };
}

// CLI
const program = new Command();
program
  .name("prepare-manual-analysis")
  .description("Produce a copy-pasteable analysis prompt bundle under _manual/")
  .requiredOption("--candidate <id>", "Candidate ID")
  .requiredOption("--version <date>", "Version date (YYYY-MM-DD)")
  .option("--force", "Overwrite existing _manual/ folder", false)
  .action(async (opts) => {
    try {
      await prepareManualAnalysis({
        candidate: opts.candidate,
        version: opts.version,
        force: opts.force,
      });
    } catch (err) {
      log.error(
        { error: err instanceof Error ? err.message : String(err) },
        "Failed to prepare manual bundle",
      );
      process.exit(1);
    }
  });

const isDirectRun =
  process.argv[1] &&
  (process.argv[1].endsWith("/prepare-manual-analysis.ts") ||
    process.argv[1].endsWith("/prepare-manual-analysis.js"));
if (isDirectRun) {
  program.parse(normalizeArgv(process.argv));
}
